version: '3.8'

services:
  sql_injection:
    build: ./challenges/sql_injection
    ports:
      - "5001:5000"

  xss:
    build: ./challenges/xss
    ports:
      - "5002:5000"

  broken_auth:
    build: ./challenges/broken_auth
    ports:
      - "5003:5000"

  prompt_injection:
    build: ./challenges/ai_prompt_injection
    ports:
      - "5005:5000"
    env_file:
      - ./challenges/ai_prompt_injection/.env

  homepage:
    build: ./homepage
    ports:
      - "5000:5000"
    env_file:
      - ./homepage/.env
