services:
  sql_injection:
    build: ./challenges/sql_injection
    ports:
      - "5001:5000"

  xss:
    build: ./challenges/xss
    ports:
      - "5002:5000"

  broken_auth:
    build: ./challenges/broken_auth
    ports:
      - "5003:5000"

  prompt_injection:
    build: ./challenges/ai_prompt_injection
    ports:
      - "5005:5000"
    environment:
      - OPENAI_API_KEY=sk-U0M0LrsjpLqkeZHAszHK0Z8hbGaeADRmcLZc6L2wnMT3BlbkFJHtWezszjjOB5O7UOkzBjkdgOCtKHhgcra1YyT22IgA
